routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('adminlte.dashboard');
});

Route::get('/kalender', function () {
    return view('kalender');
});

Route::resource('buku', 'BukuController')->middleware('auth');

Route::resource('anggota', 'AnggotaController')->middleware('auth');

Route::resource('kategori', 'KategoriController')->middleware('auth');

Route::resource('rak', 'RakController')->middleware('auth');

Route::resource('peminjaman', 'PeminjamanController')->middleware('auth');

Route::resource('pengembalian', 'PengembalianController')->middleware('auth');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Rak.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Rak extends Model
{
    protected $table = "rak";
    protected $fillable = ["no_rak", "nama_rak"]; //kolom yg mau diisi
    protected $guarded = []; //kolom yg gaboleh diisi
}

app/Http/Controllers/RakController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Rak;

class RakController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $rak = Rak::all();
        return view('rak.index', compact('rak'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('rak.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'no_rak' => 'required|unique:rak',
            'nama_rak' => 'required',
        ]);

        $rak = Rak::create([
            "no_rak" => $request["no_rak"],
            "nama_rak" => $request["nama_rak"]
        ]);

        return redirect('/rak')->with('success', 'Data Rak Berhasil Disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $rak = Rak::find($id);
        return view('rak.show', compact('rak'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $rak = Rak::find($id);
        return view('rak.edit', compact('rak'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rak = Rak::where('id', $id)->update([
            "no_rak" => $request["no_rak"],
            "nama_rak" => $request["nama_rak"]
        ]);

        return redirect('/rak')->with('success', 'Berhasil Update Data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Rak::destroy($id);
        return redirect('/rak')->with('success', 'Berhasil Menghapus Data');
    }
}

resources/views/rak/create.blade.php
@extends('adminlte.master')

@section('content')
<div class="card card-primary ml-3 mt-3 mr-3">
    <div class="card-header px-5">
        <h3 class="card-title">Buat Data Rak</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form" action="/rak" method="POST">
    @csrf
        <div class="card-body px-5">
            <div class="form-group">
                <label for="no_rak">Nomor Rak</label>
                <input type="text" class="form-control" id="no_rak" name="no_rak" value="{{old('no_rak', '')}}" placeholder="Nomor Rak...">
                @error('isbn')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="nama_rak">Nama Rak</label>
                <input type="text" class="form-control" id="nama_rak" name="nama_rak" value="{{old('nama_rak', '')}}" placeholder="Nama Rak ...">
                @error('nama_rak')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
    <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Buat</button>
        </div>
    </form>
</div>
@endsection

resources/views/rak/edit.blade.php
@extends('adminlte.master')

@section('content')
<div class="card card-primary ml-3 mt-3 mr-3">
    <div class="card-header px-5">
        <h3 class="card-title">Buat Data Rak</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form" action="/rak" method="POST">
    @csrf
    @method('PUT')
        <div class="card-body px-5">
            <div class="form-group">
                <label for="no_rak">Nomor Rak</label>
                <input type="text" class="form-control" id="no_rak" name="no_rak" value="{{old('no_rak', '')}}" placeholder="Nomor Rak...">
                @error('isbn')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="nama_rak">Nama Rak</label>
                <input type="text" class="form-control" id="nama_rak" name="nama_rak" value="{{old('nama_rak', '')}}" placeholder="Nama Rak ...">
                @error('nama_rak')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
    <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Buat</button>
        </div>
    </form>
</div>
@endsection

resources/views/rak/index.blade.php
@extends('adminlte.master')

@section('content')
<div class="mt-3 ml-3">
    <div class="card">
              <div class="card-header">
                <h3 class="card-title">Data Rak</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                @if(session('success'))
                    <div class="alert alert-success">
                        {{ session('success')}}
                    </div>
                @endif
                <a class="btn btn-primary" href="{{route('rak.create')}}">Tambah Data Rak</a>
                <table class="table table-bordered mt-2">
                  <thead>
                    <tr>
                      <th style="width: 10px">No.</th>
                      <th>Nomor Rak</th>
                      <th>Nama Rak</th>
                      <th style="width: 40px">Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    @forelse($rak as $key => $wadah)
                        <tr>
                            <td> {{ $key + 1 }} </td>
                            <td> {{ $wadah->no_rak }} </td>
                            <td> {{ $wadah->nama_rak }} </td>
                            <td style="display: flex;">
                                <a href="{{route('rak.show', ['rak' => $wadah -> id])}}" class="btn btn-info btn-sm mr-1">Show</a>
                                <a href="{{route('rak.edit', ['rak' => $wadah -> id])}}" class="btn btn-default btn-sm mr-1">Edit</a>      
                                <form action="{{route('rak.destroy', ['rak' => $wadah -> id])}}" method="post">
                                @csrf
                                @method('DELETE')
                                    <input type="submit" value="Delete" class="btn btn-danger btn-sm">
                                </form>                
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="4" align="center"> Tidak Ada Data </td>
                        </tr>
                    @endforelse
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
              <div class="card-footer clearfix">
                <ul class="pagination pagination-sm m-0 float-right">
                  <li class="page-item"><a class="page-link" href="#">«</a></li>
                  <li class="page-item"><a class="page-link" href="#">1</a></li>
                  <li class="page-item"><a class="page-link" href="#">2</a></li>
                  <li class="page-item"><a class="page-link" href="#">3</a></li>
                  <li class="page-item"><a class="page-link" href="#">»</a></li>
                </ul>
              </div>
            </div>
    </div>
@endsection

resources/views/rak/show.blade.php
@extends('adminlte.master')

@section('content')
<div class="mt-3 ml-5"> 
    <h5> Nomor Rak </h5>
    <p> {{$rak->no_rak}} </p>
    <h5> Nama Rak</h5>
    <p> {{$rak->nama_rak}} </p>
</div>
    
@endsection