routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('adminlte.dashboard');
});

Route::get('/kalender', function () {
    return view('kalender');
});

Route::resource('buku', 'BukuController')->middleware('auth');

Route::resource('anggota', 'AnggotaController')->middleware('auth');

Route::resource('kategori', 'KategoriController')->middleware('auth');

Route::resource('rak', 'RakController')->middleware('auth');

Route::resource('peminjaman', 'PeminjamanController')->middleware('auth');

Route::resource('pengembalian', 'PengembalianController')->middleware('auth');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Pengembalian.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pengembalian extends Model
{
    protected $table = "pengembalian";
    protected $fillable = ["isbn", "nama_buku", "nama_pengarang", "tahun_terbit", "status_buku", "rak_id", "kategori_id"]; //kolom yg mau diisi
    protected $guarded = []; //kolom yg gaboleh diisi
}

app/Http/Controllers/PengembalianController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Pengembalian;
use App\Anggota;
use App\Buku;

class PengembalianController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pengembalian = Pengembalian::all();
        return view('pengembalian.index', compact('pengembalian'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $buku2 = Buku::all();
        $anggota2 = Anggota::all();
        return view('pengembalian.create', compact('buku2', 'anggota2'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'tanggal_kembali' => 'required',
            'denda' => 'required',
            'deskripsi_denda' => 'required',
            'anggota_id' => 'required',
            'buku_id' => 'required'
        ]);

        $pengembalian = Pengembalian::create([
            "tanggal_kembali" => $request["tanggal_kembali"],
            "denda" => $request["denda"],
            "deskripsi_denda" => $request["deskripsi_denda"],
            "anggota_id" => $request["anggota_id"],
            "buku_id" => $request["buku_id"]
        ]);

        return redirect('/pengembalian')->with('success', 'Data Pengembalian Berhasil Disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $pengembalian = Pengembalian::find($id);
        return view('pengembalian.show', compact('pengembalian'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $pengembalian = Pengembalian::find($id);
        return view('pengembalian.edit', compact('pengembalian'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $pengembalian = Pengembalian::where('id', $id)->update([
            "tanggal_kembali" => $request["tanggal_kembali"],
            "denda" => $request["denda"],
            "deskripsi_denda" => $request["deskripsi_denda"]
        ]);

        return redirect('/pengembalian')->with('success', 'Berhasil Update Data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Pengembalian::destroy($id);
        return redirect('/pengembalian')->with('success', 'Berhasil Menghapus Data');
    }
}

resources/views/pengembalian/create.blade.php
@extends('adminlte.master')

@section('content')
<div class="card card-primary ml-3 mt-3 mr-3">
    <div class="card-header px-5">
        <h3 class="card-title">Buat Data Rak</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form" action="/rak" method="POST">
    @csrf
        <div class="card-body px-5">
            <div class="form-group">
                <label for="tanggal_kembali">Tanggal Pengembalian</label>
                <input type="date" id="tanggal_kembali" name="tanggal_kembali" value="{{old('tanggal_kembali', '')}}">
                @error('tanggal_kembali')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="denda">Denda</label>
                <input type="text" class="form-control" id="denda" name="denda" value="{{old('denda', '')}}" placeholder="Denda ...">
                @error('isbn')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="deskripsi_denda">Deskripsi Denda</label>
                <input type="text" class="form-control" id="deskripsi_denda" name="deskripsi_denda" value="{{old('deskripsi_denda', '')}}" placeholder="Deskripsi Denda ...">
                @error('deskripsi_denda')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="buku">Buku</label>
                <select name="buku_id" class="form-control">
                    <option>--Pilih--</option>
                    @foreach($buku2 as $item)
                    <option value="{{$item->id}}">{{$item->nama_buku}}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="anggota">Anggota</label>
                <select name="anggota_id" class="form-control">
                    <option>--Pilih--</option>
                    @foreach($anggota2 as $item)
                    <option value="{{$item->id}}">{{$item->nama}}</option>
                    @endforeach
                </select>
            </div>
    <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Buat</button>
        </div>
    </form>
</div>
@endsection

resources/views/pengembalian/edit.blade.php
@extends('adminlte.master')

@section('content')
<div class="card card-primary ml-3 mt-3 mr-3">
    <div class="card-header px-5">
        <h3 class="card-title">Buat Data Rak</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form" action="/rak" method="POST">
    @csrf
    @method('PUT')
        <div class="card-body px-5">
            <div class="form-group">
                <label for="tanggal_kembali">Tanggal Pengembalian</label>
                <input type="date" id="tanggal_kembali" name="tanggal_kembali" value="{{old('tanggal_kembali', '')}}">
                @error('tanggal_kembali')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="denda">Denda</label>
                <input type="text" class="form-control" id="denda" name="denda" value="{{old('denda', '')}}" placeholder="Denda ...">
                @error('isbn')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="deskripsi_denda">Deskripsi Denda</label>
                <input type="text" class="form-control" id="deskripsi_denda" name="deskripsi_denda" value="{{old('deskripsi_denda', '')}}" placeholder="Deskripsi Denda ...">
                @error('deskripsi_denda')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="anggota">Anggota</label>
                <select name="anggota_id" class="form-control">
                    <option>--Pilih--</option>
                    @foreach($anggota2 as $item)
                    <option value="{{$item->id}}">{{$item->nama}}</option>
                    @endforeach
                </select>
            </div>
    <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Buat</button>
        </div>
    </form>
</div>
@endsection

resources/views/pengembalian/index.blade.php
@extends('adminlte.master')

@section('content')
<div class="mt-3 ml-3">
    <div class="card">
              <div class="card-header">
                <h3 class="card-title">Daftar Pengembalian</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                @if(session('success'))
                    <div class="alert alert-success">
                        {{ session('success')}}
                    </div>
                @endif
                <a class="btn btn-primary" href="{{route('pengembalian.create')}}">Tambah Data Pengembalian</a>
                <table class="table table-bordered mt-2">
                  <thead>
                    <tr>
                      <th style="width: 10px">No.</th>
                      <th>Anggota</th>
                      <th>Buku</th>
                      <th>Tanggal Pengembalian</th>
                      <th>Denda</th>
                      <th>Deskripsi Denda</th>
                      <th style="width: 40px">Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    @forelse($pengembalian as $key => $kembali)
                        <tr>
                            <td> {{ $key + 1 }} </td>
                            <td> {{ $kembali->anggota_id }} </td>
                            <td> {{ $kembali->buku_id }} </td>
                            <td> {{ $kembali->tanggal_kembali }} </td>
                            <td> {{ $kembali->denda }} </td>
                            <td> {{ $kembali->deskripsi_denda }} </td>
                            <td style="display: flex;"> 
                                <a href="{{route('buku.show', ['buku' => $book -> id])}}" class="btn btn-info btn-sm mr-1">Show</a>
                                <a href="{{route('buku.edit', ['buku' => $book -> id])}}" class="btn btn-default btn-sm mr-1">Edit</a>      
                                <form action="{{route('buku.destroy', ['buku' => $book -> id])}}" method="post">
                                @csrf
                                @method('DELETE')
                                    <input type="submit" value="Delete" class="btn btn-danger btn-sm">
                                </form>                
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="7" align="center"> Tidak Ada Data </td>
                        </tr>
                    @endforelse
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
              <div class="card-footer clearfix">
                <ul class="pagination pagination-sm m-0 float-right">
                  <li class="page-item"><a class="page-link" href="#">«</a></li>
                  <li class="page-item"><a class="page-link" href="#">1</a></li>
                  <li class="page-item"><a class="page-link" href="#">2</a></li>
                  <li class="page-item"><a class="page-link" href="#">3</a></li>
                  <li class="page-item"><a class="page-link" href="#">»</a></li>
                </ul>
              </div>
            </div>
    </div>
@endsection

resources/views/pengembalian/show.blade.php
@extends('adminlte.master')

@section('content')
<div class="mt-3 ml-5"> 
    <h5> Anggota </h5>
    <p> {{$pengembalian->anggota_id}} </p>
    <h5> Buku </h5>
    <p> {{$pengembalian->buku_id}} </p>
    <h5> Tanggal Pengembalian </h5>
    <p> {{$pengembalian->tanggal_kembali}} </p>
    <h5> Denda </h5>
    <p> {{$pengembalian->denda}} </p>
    <h5> Deskripsi Denda </h5>
    <p> {{$pengembalian->deskripsi_denda}} </p>
</div>
    
@endsection