routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('adminlte.dashboard');
});

Route::get('/kalender', function () {
    return view('kalender');
});

Route::resource('buku', 'BukuController')->middleware('auth');

Route::resource('anggota', 'AnggotaController')->middleware('auth');

Route::resource('kategori', 'KategoriController')->middleware('auth');

Route::resource('rak', 'RakController')->middleware('auth');

Route::resource('peminjaman', 'PeminjamanController')->middleware('auth');

Route::resource('pengembalian', 'PengembalianController')->middleware('auth');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Anggota.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Anggota extends Model
{
    protected $table = "anggota";
    protected $fillable = ["nama", "jenis_kelamin", "tgl_lahir", "status"]; //kolom yg mau diisi
    protected $guarded = ["foto_profil"]; //kolom yg gaboleh diisi
}

app/Http/Controllers/AnggotaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Anggota;

class AnggotaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $anggota = Anggota::all();
        return view('anggota.index', compact('anggota'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('anggota.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required|unique:anggota',
            'jenis_kelamin' => 'required',
            'tgl_lahir' => 'required',
            'status' => 'required'
        ]);

        $anggota = Anggota::create([
            "nama" => $request["nama"],
            "jenis_kelamin" => $request["jenis_kelamin"],
            "tgl_lahir" => $request["tgl_lahir"],
            "status" => $request["status"]
        ]);

        return redirect('/anggota')->with('success', 'Data Anggota Berhasil Disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $anggota = Anggota::find($id);
        return view('anggota.show', compact('anggota'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $anggota = Anggota::find($id);
        return view('anggota.edit', compact('anggota'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $anggota = Anggota::where('id', $id)->update([
            "nama" => $request["nama"],
            "jenis_kelamin" => $request["jenis_kelamin"],
            "tgl_lahir" => $request["tgl_lahir"],
            //"foto_profil" => $request["foto_profil"],
            "status" => $request["status"]
        ]);

        return redirect('/anggota')->with('success', 'Berhasil Update Data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Anggota::destroy($id);
        return redirect('/anggota')->with('success', 'Berhasil Menghapus Data');
    }

    //public function upload(Request $request){
      //  $file = $request->file('image');
        //$nama_file = $file->getClientOriginalName();
        //$extension = $file->getClientOriginalExtension();
        //$size = $file->getSize();
        //$path = 'storage';
        //$file->move($path,$file->getClientOriginalName());
        //return redirect()->back->withSuccess('success','Foto Berhasil Diupload');
    //}
}

resources/views/anggota/create.blade.php
@extends('adminlte.master')

@section('content')
<div class="card card-primary ml-3 mt-3 mr-3">
    <div class="card-header px-5">
        <h3 class="card-title">Buat Data Anggota</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form" action="/anggota" method="POST">
    @csrf
        <div class="card-body px-5">
            <div class="form-group">
                <label for="nama">Nama</label>
                <input type="text" class="form-control" id="nama" name="nama" value="{{old('nama', '')}}" placeholder="Nama ...">
                @error('isbn')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="jenis_kelamin">Jenis Kelamin (Laki-laki/Perempuan)</label>
                <input type="text" class="form-control" id="jenis_kelamin" name="jenis_kelamin" value="{{old('jenis_kelamin', '')}}" placeholder="Jenis Kelamin ...">
                @error('jenis_kelamin')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="tgl_lahir">Tanggal Lahir</label><br>
                <input type="date" id="tgl_lahir" name="tgl_lahir" value="{{old('tgl_lahir', '')}}">
                @error('tgl_lahir')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="foto_profil">Foto Profil</label>
                <div class="col-md-6 mr-3">
                    <div class="card">
                        <div class="card-body">
                        <h4 class="card-title">Upload image</h4>
                        <p class="card-text">
                            <form action="/anggota/upload" method="post" enctype="multipart/form-data">
                                {{csrf_field()}}
                                <input type="file" name="image" class="form-control">
                                <br/>
                                <button type="submit" class="btn btn-primary form-control">Upload</button>
                            </form>
                        </p>
                        </div>
                    </div>
                </div>
                @error('foto_profil')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label for="status">Status</label>
                <input type="text" class="form-control" id="status" name="status" value="{{old('status', '')}}" placeholder="Status ...">
                @error('status')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
    <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Buat</button>
        </div>
    </form>
</div>
@endsection

resources/views/anggota/edit.blade.php
@extends('adminlte.master')

@section('content')
<div class="card card-primary ml-3 mt-3 mr-3">
    <div class="card-header px-5">
        <h3 class="card-title">Buat Data Anggota</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form" action="/anggota/{{$anggota->id}}" method="POST">
    @csrf
    @method('PUT')
        <div class="card-body px-5">
            <div class="form-group">
                <label for="nama">Nama</label>
                <input type="text" class="form-control" id="nama" name="nama" value="{{old('nama', '')}}" placeholder="Nama ...">
                @error('isbn')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="jenis_kelamin">Jenis Kelamin (Laki-laki/Perempuan)</label>
                <input type="text" class="form-control" id="jenis_kelamin" name="jenis_kelamin" value="{{old('jenis_kelamin', '')}}" placeholder="Jenis Kelamin ...">
                @error('jenis_kelamin')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="tgl_lahir">Tanggal Lahir</label><br>
                <input type="date" id="tgl_lahir" name="tgl_lahir" value="{{old('tgl_lahir', '')}}">
                @error('tgl_lahir')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="foto_profil">Foto Profil</label>
                <div class="col-md-6 mr-3">
                    <div class="card">
                        <div class="card-body">
                        <h4 class="card-title">Upload image</h4>
                        <p class="card-text">
                            <form action="/anggota/upload" method="post" enctype="multipart/form-data">
                                {{csrf_field()}}
                                <input type="file" name="image" class="form-control">
                                <br/>
                                <button type="submit" class="btn btn-primary form-control">Upload</button>
                            </form>
                        </p>
                        </div>
                    </div>
                </div>
                @error('foto_profil')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label for="status">Status</label>
                <input type="text" class="form-control" id="status" name="status" value="{{old('status', '')}}" placeholder="Status ...">
                @error('status')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
    <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Buat</button>
        </div>
    </form>
</div>
@endsection

resources/views/anggota/index.blade.php
@extends('adminlte.master')

@section('content')
<div class="mt-3 ml-3">
    <div class="card">
              <div class="card-header">
                <h3 class="card-title">Data Anggota</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                @if(session('success'))
                    <div class="alert alert-success">
                        {{ session('success')}}
                    </div>
                @endif
                <a class="btn btn-primary" href="{{route('anggota.create')}}">Tambah Data Anggota</a>
                <table class="table table-bordered mt-2">
                  <thead>
                    <tr>
                      <th style="width: 10px">No.</th>
                      <th>Nama</th>
                      <th>Jenis Kelamin</th>
                      <th>Tanggal Lahir</th>
                      <th>Foto Profil</th>
                      <th>Status</th>
                      <th style="width: 40px">Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    @forelse($anggota as $key => $member)
                        <tr>
                            <td> {{ $key + 1 }} </td>
                            <td> {{ $member->nama }} </td>
                            <td> {{ $member->jenis_kelamin }} </td>
                            <td> {{ $member->tgl_lahir }} </td>
                            <td> {{ $member->null }} </td>
                            <td> {{ $member->status }} </td>
                            <td style="display: flex;">
                                <a href="{{route('anggota.show', ['anggotum' => $member -> id])}}" class="btn btn-info btn-sm mr-1">Show</a>
                                <a href="{{route('anggota.edit', ['anggotum' => $member -> id])}}" class="btn btn-default btn-sm mr-1">Edit</a>      
                                <form action="{{route('anggota.destroy', ['anggotum' => $member -> id])}}" method="post">
                                @csrf
                                @method('DELETE')
                                    <input type="submit" value="Delete" class="btn btn-danger btn-sm">
                                </form>                
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="7" align="center"> Tidak Ada Data </td>
                        </tr>
                    @endforelse
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
              <div class="card-footer clearfix">
                <ul class="pagination pagination-sm m-0 float-right">
                  <li class="page-item"><a class="page-link" href="#">«</a></li>
                  <li class="page-item"><a class="page-link" href="#">1</a></li>
                  <li class="page-item"><a class="page-link" href="#">2</a></li>
                  <li class="page-item"><a class="page-link" href="#">3</a></li>
                  <li class="page-item"><a class="page-link" href="#">»</a></li>
                </ul>
              </div>
            </div>
    </div>
@endsection

resources/views/anggota/show.blade.php
@extends('adminlte.master')

@section('content')
<div class="mt-3 ml-5"> 
    <h5> Nama </h5>
    <p> {{$anggota->nama}} </p>
    <h5> Jenis Kelamin </h5>
    <p> {{$anggota->jenis_kelamin}} </p>
    <h5> Tanggal Lahir </h5>
    <p> {{$anggota->tgl_lahir}} </p>
    <h5> Foto Profil </h5>
    <h5> Status </h5>
    <p> {{$anggota->status}} </p>
</div>
    
@endsection